<a href="https://colab.research.google.com/github/mubinulislam/python_basics/blob/main/pandas_Essentials_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
# CREATING SERIES
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
#CREATING A DATA FRAME
data={'Name':['Alice','Bob','Charlie','David'],
      'Age':[25,30,35,40],
      'city':['New York','San Francisco','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age           city
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago

In [5]:
df

      Name  Age           city
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago

In [8]:
df1=pd.read_csv('medium_dataset.csv')

In [9]:
#View first few rows
print(df1.head)

<bound method NDFrame.head of       ID      Name  Age     City  Score
0      1    Name_1   19   City_1   51.5
1      2    Name_2   20   City_2   53.0
2      3    Name_3   21   City_3   54.5
3      4    Name_4   22   City_4   56.0
4      5    Name_5   23   City_5   57.5
..   ...       ...  ...      ...    ...
495  496  Name_496   34  City_46   99.0
496  497  Name_497   35  City_47  100.5
497  498  Name_498   36  City_48  102.0
498  499  Name_499   37  City_49  103.5
499  500  Name_500   38   City_0   50.0

[500 rows x 5 columns]>

In [10]:
df1

      ID      Name  Age     City  Score
0      1    Name_1   19   City_1   51.5
1      2    Name_2   20   City_2   53.0
2      3    Name_3   21   City_3   54.5
3      4    Name_4   22   City_4   56.0
4      5    Name_5   23   City_5   57.5
..   ...       ...  ...      ...    ...
495  496  Name_496   34  City_46   99.0
496  497  Name_497   35  City_47  100.5
497  498  Name_498   36  City_48  102.0
498  499  Name_499   37  City_49  103.5
499  500  Name_500   38   City_0   50.0

[500 rows x 5 columns]

In [11]:
#View last few rows
print(df1.tail())

      ID      Name  Age     City  Score
495  496  Name_496   34  City_46   99.0
496  497  Name_497   35  City_47  100.5
497  498  Name_498   36  City_48  102.0
498  499  Name_499   37  City_49  103.5
499  500  Name_500   38   City_0   50.0

In [12]:
#Get information about the data frame
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes
None

In [14]:
#Generate Descriptive Stastics
print(df.describe())

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

# **Indexing And SLicing**

In [15]:
#Selecting single column by label
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [19]:
#Selecting a single column by position
print(df.iloc[0:3,0])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [20]:
df

      Name  Age           city
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago

In [22]:
#Selecting rows and columns by position. It can also be done by column field names insted of the position numbers.
print(df.iloc[0:4,0:2])

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

# **Missing data handling**

In [23]:
#CREATING A DATA FRAME WITH MISSING VALUE
data={'Name':['Alice','Bob',None,'David'],
      'Age':[25,30,35,40],
      'city':['New York','San Francisco','Los Angeles','Chicago']}
df2=pd.DataFrame(data)
print(df2)

    Name  Age           city
0  Alice   25       New York
1    Bob   30  San Francisco
2   None   35    Los Angeles
3  David   40        Chicago

In [25]:
#Drop rows with missing value
df2.dropna()

    Name  Age           city
0  Alice   25       New York
1    Bob   30  San Francisco
3  David   40        Chicago

In [26]:
#Fill missing value with specific values
df2.fillna('Charlie')

      Name  Age           city
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago